import React from "react";
import type { Metadata } from "next";
import { Button, Htag, P, Tag } from "@/components";
import { ArrowMode, ButtonMode } from "@/components/Button/types";
import { TagColor } from "@/components/Tag/types";

export const metadata: Metadata = {
  title: "page",
  description: "Generated by create next app",
};

export default function Home(): React.JSX.Element {
  return (
    <div>
      <Htag tag="h1">HTAG</Htag>
      <Button appearance={ButtonMode.primary}>button</Button>
      <Button appearance={ButtonMode.primary} arrow={ArrowMode.down}>
        button
      </Button>
      <P size={"s"}>S</P>
      <P>M</P>
      <P size={"l"}>L</P>
      <Tag size={"m"} color={TagColor.primary} href={"https://google.com"}>
        TEST
      </Tag>
    </div>
  );
}
