import React from "react";
import type { Metadata } from "next";
import { Button, Htag } from "@/components";

export const metadata: Metadata = {
  title: "page",
  description: "Generated by create next app",
};

export default function Home(): React.JSX.Element {
  return (
    <div>
      <Htag tag="h1">HTAG</Htag>
      <Button appearance={"primary"}>button</Button>
      <Button appearance={"ghost"}>button</Button>
    </div>
  );
}
